Import turtle

# Create the Sun
# sun = turtle.Turtle()
# sun.shape("circle")
# sun.color("yellow")
# sun.shapesize()
# sun.penup()

# # Create the planets
# mercury = turtle.Turtle()
# mercury.color("gray")
# mercury.shape("circle")
# mercury.speed(3)
# mercury.penup()
# mercury.goto(50, 0)
# mercury.pendown()

# venus = turtle.Turtle()
# venus.color("orange")
# venus.shape("circle")
# venus.speed(1.5)
# venus.penup()
# venus.goto(100, 0)
# venus.pendown()

# earth = turtle.Turtle()
# earth.color("blue")
# earth.shape("circle")
# earth.speed(1)
# earth.penup()
# earth.goto(150, 0)
# earth.pendown()

# mars = turtle.Turtle()
# mars.color("red")
# mars.shape("circle")
# mars.speed(0.8)
# mars.penup()
# mars.goto(200, 0)
# mars.pendown()

# jupiter = turtle.Turtle()
# jupiter.color("orange")
# jupiter.shape("circle")
# jupiter.speed(0.5)
# jupiter.penup()
# jupiter.goto(250, 0)
# jupiter.pendown()

# saturn = turtle.Turtle()
# saturn.color("gold")
# saturn.shape("circle")
# saturn.speed(0.3)
# saturn.penup()
# saturn.goto(300, 0)
# saturn.pendown()

# uranus = turtle.Turtle()
# uranus.color("light blue")
# uranus.shape("circle")
# uranus.speed(0.2)
# uranus.penup()
# uranus.goto(350, 0)
# uranus.pendown()

# neptune = turtle.Turtle()
# neptune.color("dark blue")
# neptune.shape("circle")
# neptune.speed(0.1)
# neptune.penup()
# neptune.goto(400, 0)
# neptune.pendown()

# pluto = turtle.Turtle()
# pluto.color("light gray")
# pluto.shape("circle")
# pluto.speed(0.05)
# pluto.penup()
# pluto.goto(450, 0)
# pluto.pendown()

# # Create the moon
# moon = turtle.Turtle()
# moon.color("white")
# moon.shape("circle")
# moon.speed(0.5)
# moon.penup()
# moon.goto(150, -30)
# moon.pendown()
